#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require __DIR__ . '/app/vendor/autoload.php';
require(__DIR__ . '/app/functions.php');

$dotenv = \Dotenv\Dotenv::createImmutable(dirname(__DIR__));
$dotenv->load();

defined('YII_DEBUG') or define('YII_DEBUG', env('YII_DEBUG'));
defined('YII_ENV') or define('YII_ENV', env('YII_ENV', 'prod'));

require __DIR__ . '/vapp/endor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/app/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
