<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\web\IdentityInterface;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $fullname
 * @property string $email
 * @property string $auth_key
 * @property string $password_hash
 */
class User extends ActiveRecord implements IdentityInterface
{

    public $password;

    //public $username;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    public function init()
    {
        $this->on(ActiveRecord::EVENT_BEFORE_INSERT, [$this, 'beforeInsert']);
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email', 'auth_key', 'password_hash'], 'required'],
            [['first_name', 'last_name', 'password_hash'], 'string', 'max' => 60],
            [['email'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['email'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'first_name' => Yii::t('app', 'First Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'email' => Yii::t('app', 'Email'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'password_hash' => Yii::t('app', 'Password Hash'),
        ];
    }

    public function getFullName(){
        return $this->first_name . ' ' . $this->last_name;
    }

    public function validatePassword($password)
    {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password_hash);
    }

    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    public function beforeInsert()
    {
        $this->auth_key = Yii::$app->getSecurity()->generateRandomString(32);
        $this->password_hash = Yii::$app->getSecurity()->generatePasswordHash($this->password);
    }

    public static function findIdentity($id){
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null){
        throw new NotSupportedException('Method "' . __CLASS__ . '::' . __METHOD__ . '" is not implemented.');
    }

    public function getId(){
        return $this->getPrimaryKey();
    }

    public function getAuthKey(){
        return $this->getAttribute('auth_key');
    }

    public function validateAuthKey($authKey){
        return $this->getAttribute('auth_key') === $authKey;
    }

}
